import React from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Rocket, Target, Heart, Sparkles, AlertTriangle, ChevronDown, LucideIcon } from 'lucide-react';
import { cn } from '@/lib/utils';

interface KeyTakeaway {
  label: string;
  description: string;
  icon: LucideIcon;
  colorClass: string;
}

interface HolisticSummary {
  overallScore: number;
  tierName: string;
  tierPercentile: string;
  profileSummary: string;
  coreIdentity: KeyTakeaway;
  competitivePosition: KeyTakeaway;
  narrativeTheme: KeyTakeaway;
  biggestDifferentiator: KeyTakeaway;
  criticalGap: KeyTakeaway;
}

// IMPORTANT: Hard-coded mock data representing a holistic portfolio analysis
// In production, this would be generated by AI analyzing the user's complete portfolio
// and synthesizing patterns across all dimensions, activities, and achievements
const MOCK_HOLISTIC_SUMMARY: HolisticSummary = {
  overallScore: 8.2,
  tierName: 'Diamond Achiever',
  tierPercentile: 'Top 15%',
  profileSummary: 'You present as a community-focused STEM leader with demonstrated technical expertise, sustained volunteer commitment, and emerging research capabilities. Your portfolio shows cross-domain versatility, positioning you competitively for Top 20 schools with reach potential for Top 10.',
  coreIdentity: {
    label: 'STEM Leader & Community Catalyst',
    description: 'You consistently combine technical projects with community service, showing you can lead in both contexts.',
    icon: Rocket,
    colorClass: 'border-primary',
  },
  competitivePosition: {
    label: 'Strong T20, Reach for T10',
    description: 'Your profile aligns well with schools ranked 11-20. Stanford/MIT are reaches; schools like Duke/Northwestern are targets.',
    icon: Target,
    colorClass: 'border-purple-500',
  },
  narrativeTheme: {
    label: 'Using Technology to Democratize Access',
    description: 'Your story centers on leveraging technical skills to create opportunities for underserved communities.',
    icon: Heart,
    colorClass: 'border-green-500',
  },
  biggestDifferentiator: {
    label: 'Cross-Domain Leadership (Tech + Community)',
    description: 'Unlike most STEM students focused purely on research, you balance technical depth with genuine community impact.',
    icon: Sparkles,
    colorClass: 'border-orange-500',
  },
  criticalGap: {
    label: 'Need Quantifiable Impact Metrics',
    description: 'Your community activities lack specific numbers (people served, hours, outcomes), making impact hard to assess.',
    icon: AlertTriangle,
    colorClass: 'border-destructive',
  },
};

export const HolisticPortfolioHero: React.FC = () => {
  const summary = MOCK_HOLISTIC_SUMMARY;
  const takeaways = [
    summary.coreIdentity,
    summary.competitivePosition,
    summary.narrativeTheme,
    summary.biggestDifferentiator,
    summary.criticalGap,
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-accent/5 to-background py-12 px-4">
      <div className="max-w-6xl mx-auto space-y-12">
        {/* Page Title */}
        <div className="text-center space-y-2">
          <h1 className="text-4xl md:text-5xl font-bold text-foreground">
            Your Portfolio at a Glance
          </h1>
          <p className="text-muted-foreground text-lg">
            A comprehensive synthesis of your application profile
          </p>
        </div>

        {/* Overall Score Circle */}
        <div className="flex justify-center">
          <div className="relative">
            <div className="w-48 h-48 md:w-56 md:h-56 rounded-full border-8 border-primary flex flex-col items-center justify-center bg-card shadow-xl">
              <div className="text-6xl md:text-7xl font-bold text-foreground">
                {summary.overallScore}
              </div>
              <div className="text-sm text-muted-foreground mt-1">
                out of 10
              </div>
            </div>
            <div className="absolute -bottom-8 left-1/2 -translate-x-1/2 w-max">
              <div className="bg-primary text-primary-foreground px-6 py-2 rounded-full font-semibold text-lg shadow-lg">
                {summary.tierName}
              </div>
              <div className="text-center text-sm text-muted-foreground mt-2">
                {summary.tierPercentile}
              </div>
            </div>
          </div>
        </div>

        {/* Profile Summary */}
        <div className="mt-16">
          <Card className="bg-card shadow-lg border-2">
            <div className="p-8 md:p-10">
              <h2 className="text-2xl font-bold text-foreground mb-4 text-center">
                Your Candidate Profile
              </h2>
              <p className="text-lg text-foreground/90 leading-relaxed text-center max-w-4xl mx-auto">
                {summary.profileSummary}
              </p>
            </div>
          </Card>
        </div>

        {/* Five Key Takeaways */}
        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-foreground text-center mb-6">
            Five Key Takeaways
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {takeaways.map((takeaway, index) => {
              const Icon = takeaway.icon;
              return (
                <Card
                  key={index}
                  className={cn(
                    'bg-card shadow-md hover:shadow-lg transition-shadow border-l-4',
                    takeaway.colorClass
                  )}
                >
                  <div className="p-6 flex gap-4">
                    <div className="flex-shrink-0">
                      <div className="w-12 h-12 rounded-lg bg-accent/10 flex items-center justify-center">
                        <Icon className="w-6 h-6 text-foreground" />
                      </div>
                    </div>
                    <div className="flex-1 space-y-2">
                      <h3 className="text-base font-semibold text-foreground">
                        {takeaway.label}
                      </h3>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {takeaway.description}
                      </p>
                    </div>
                  </div>
                </Card>
              );
            })}
          </div>
        </div>

        {/* Scroll Indicator */}
        <div className="flex flex-col items-center gap-4 pt-8 pb-4">
          <p className="text-muted-foreground text-sm">
            Scroll to explore detailed insights
          </p>
          <Button
            variant="ghost"
            size="sm"
            className="animate-bounce"
            onClick={() => window.scrollBy({ top: window.innerHeight, behavior: 'smooth' })}
          >
            <ChevronDown className="w-6 h-6" />
          </Button>
        </div>
      </div>
    </div>
  );
};
