import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { InsightCard, InsightCardProps } from './InsightCard';
import { TimelineVisualization } from './insights/TimelineVisualization';
import { ComparisonVisualization } from './insights/ComparisonVisualization';
import { NetworkVisualization } from './insights/NetworkVisualization';
import { 
  BookOpen,
  Users,
  Trophy,
  GraduationCap,
  Code,
  Lightbulb
} from 'lucide-react';

// MOCK DATA - Hard-coded insight examples demonstrating the types of valuable analysis
// the system can provide. In production, these would be generated by AI analysis of the user's
// actual portfolio data, identifying non-obvious patterns, gaps, and opportunities.
const MOCK_INSIGHTS: InsightCardProps[] = [
  {
    type: 'pattern',
    headline: 'Consistent Leadership Through Technology',
    insight: 'Your portfolio shows a recurring pattern: you consistently take leadership roles in technical contexts, but rarely in non-technical settings. This suggests your confidence as a leader is domain-specific.',
    significance: 'Admissions officers look for versatile leadership. While your tech leadership is strong, diversifying into non-technical leadership roles (student government, community organizing, arts) would demonstrate broader capability.',
    evidence: [
      { label: '3 Technical Team Lead roles', icon: Code },
      { label: '5 Hackathon organizing roles', icon: Trophy },
      { label: '0 Non-technical leadership positions', icon: Users },
    ],
    visualization: (
      <NetworkVisualization
        centerNodeId="tech-lead"
        nodes={[
          { id: 'tech-lead', label: 'Tech Leadership', type: 'primary', connections: ['robotics', 'coding', 'hackathon'] },
          { id: 'robotics', label: 'Robotics Captain', type: 'secondary', connections: [] },
          { id: 'coding', label: 'CS Club President', type: 'secondary', connections: [] },
          { id: 'hackathon', label: 'Hackathon Organizer', type: 'secondary', connections: [] },
        ]}
      />
    ),
    action: {
      label: 'Explore Non-Technical Leadership Opportunities',
      onClick: () => console.log('Navigate to opportunities'),
    },
    priority: 'critical',
    impactScore: 9,
  },
  {
    type: 'trajectory',
    headline: 'Accelerating Research Sophistication',
    insight: 'Your research projects show rapid progression from basic literature reviews (Grade 9) to original experimental design (Grade 11). The pace of growth is significantly faster than typical student researchers.',
    significance: 'This trajectory demonstrates genuine intellectual curiosity and self-directed learning. It\'s a stronger signal than any single prestigious program, because it shows intrinsic motivation rather than just access to resources.',
    evidence: [
      { label: 'Grade 9: School science fair', icon: Trophy },
      { label: 'Grade 10: University lab internship', icon: GraduationCap },
      { label: 'Grade 11: Independent research publication', icon: BookOpen },
    ],
    visualization: (
      <TimelineVisualization
        events={[
          { date: 'Fall 2022', label: 'Science Fair Project', status: 'completed', description: 'Basic experimental design on plant growth' },
          { date: 'Summer 2023', label: 'University Lab Internship', status: 'completed', description: 'Assisted PhD student with data collection' },
          { date: 'Fall 2023', label: 'Independent Research', status: 'completed', description: 'Designed novel experiment on microplastics' },
          { date: 'Spring 2024', label: 'Research Publication', status: 'current', description: 'Paper under review at peer-reviewed journal' },
          { date: 'Summer 2024', label: 'Research Conference', status: 'upcoming', description: 'Invited to present at regional symposium' },
        ]}
      />
    ),
    priority: 'high',
    impactScore: 8,
  },
  {
    type: 'gap',
    headline: 'Missing Quantitative Impact Metrics',
    insight: 'You list 6 community service activities, but only 2 include specific numbers (hours, people served, funds raised). This makes it difficult to assess the true scale and significance of your community work.',
    significance: 'Without metrics, admissions officers may undervalue your community impact. Adding concrete numbers transforms "volunteered at food bank" into "served 200+ families weekly for 18 months" – a much stronger claim.',
    evidence: [
      { label: '6 Community activities listed', icon: Users },
      { label: 'Only 2 have quantitative metrics', icon: Trophy },
      { label: '4 activities lack measurable impact', icon: Users },
    ],
    action: {
      label: 'Add Metrics to Community Activities',
      onClick: () => console.log('Navigate to activities'),
    },
    priority: 'high',
    impactScore: 7,
  },
  {
    type: 'strength',
    headline: 'Rare Cross-Disciplinary Connector',
    insight: 'You\'re one of the few students who combines STEM research with creative writing awards. This intersection is unusual and memorable – only ~3% of applicants show genuine depth in both technical and creative fields.',
    significance: 'Cross-disciplinary students are highly valued because they bring diverse perspectives to campus discussions. Your combination of scientific rigor and creative expression suggests you can bridge different academic communities.',
    evidence: [
      { label: '2 Science research projects', icon: BookOpen },
      { label: '3 Writing competition awards', icon: Trophy },
      { label: 'Published in literary magazine', icon: Lightbulb },
    ],
    priority: 'high',
    impactScore: 9,
  },
  {
    type: 'comparison',
    headline: 'Above-Average Activity Depth, Below-Average Breadth',
    insight: 'Compared to admitted students, you show exceptional depth (3+ years commitment) but limited breadth (only 4 activity categories vs. typical 6-7). You\'re highly focused, but perhaps too narrow.',
    significance: 'Selective colleges want both depth AND breadth. Your depth is excellent and shouldn\'t be sacrificed, but adding 1-2 activities in unexplored areas (arts, athletics, etc.) would round out your profile without diluting focus.',
    evidence: [
      { label: 'Average commitment: 3.2 years', icon: Trophy },
      { label: 'Activity categories: 4 vs typical 6-7', icon: Users },
    ],
    visualization: (
      <ComparisonVisualization
        items={[
          { label: 'Activity Depth', yourValue: 8, averageValue: 6, unit: '/10', max: 10 },
          { label: 'Activity Breadth', yourValue: 4, averageValue: 6, unit: ' categories', max: 10 },
          { label: 'Time Commitment', yourValue: 18, averageValue: 12, unit: ' hrs/week', max: 25 },
        ]}
      />
    ),
    priority: 'medium',
    impactScore: 6,
  },
  {
    type: 'opportunity',
    headline: 'Untapped Research Publication Potential',
    insight: 'Your independent research on microplastics filtration has the sophistication and novelty to be submitted to peer-reviewed journals. Currently, you\'re underselling it by only listing it as a "project."',
    significance: 'A publication, even if not in a top-tier journal, dramatically increases credibility. It shows you\'ve engaged with the scientific review process and your work meets professional standards. This separates you from students who do "research" that\'s never externally validated.',
    evidence: [
      { label: 'Original experimental design', icon: Lightbulb },
      { label: 'Novel findings on filtration efficiency', icon: BookOpen },
      { label: 'Mentor willing to co-author', icon: Users },
    ],
    action: {
      label: 'Research Journal Submission Guide',
      onClick: () => console.log('Open guide'),
    },
    priority: 'medium',
    impactScore: 8,
  },
  {
    type: 'correlation',
    headline: 'Teaching Experience Amplifies Leadership Claims',
    insight: 'There\'s a strong correlation in your portfolio: activities where you taught others (tutoring, workshop leading) are also where you showed the most measurable impact. This suggests teaching is a core strength you should emphasize.',
    significance: 'Teaching requires clarity of thought, empathy, and patience – all highly valued traits. By explicitly framing yourself as an "educator" in your personal statement, you can create a coherent narrative that ties together seemingly disparate activities.',
    evidence: [
      { label: 'Tutored 15 students in math', icon: Users },
      { label: 'Led 3 coding workshops', icon: Code },
      { label: 'Trained new robotics team members', icon: GraduationCap },
    ],
    priority: 'medium',
    impactScore: 7,
  },
  {
    type: 'risk',
    headline: 'GPA Dip in Junior Year Needs Context',
    insight: 'Your GPA dropped from 3.95 to 3.7 in junior year fall semester, coinciding with increased extracurricular commitments. Without explanation, this looks like poor time management. But the timing suggests you prioritized meaningful activities.',
    significance: 'Admissions officers will notice this dip. Proactively addressing it in the Additional Information section – explaining you took on leadership roles that required significant time – reframes it as a deliberate choice rather than academic struggle.',
    evidence: [
      { label: 'GPA: 3.95 → 3.70', icon: Trophy },
      { label: 'Same semester: 3 new leadership roles', icon: Users },
    ],
    action: {
      label: 'Draft Explanation for Additional Info',
      onClick: () => console.log('Open draft tool'),
    },
    priority: 'critical',
    impactScore: 9,
  },
];

export const PortfolioOverview = () => {
  const [selectedType, setSelectedType] = useState<'all' | InsightCardProps['type']>('all');
  const [sortBy, setSortBy] = useState<'priority' | 'impact'>('priority');

  const filteredInsights = selectedType === 'all' 
    ? MOCK_INSIGHTS 
    : MOCK_INSIGHTS.filter(i => i.type === selectedType);

  const sortedInsights = [...filteredInsights].sort((a, b) => {
    if (sortBy === 'priority') {
      const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    }
    return (b.impactScore || 0) - (a.impactScore || 0);
  });

  const insightTypes = [
    { value: 'all', label: 'All Insights', count: MOCK_INSIGHTS.length },
    { value: 'pattern', label: 'Patterns', count: MOCK_INSIGHTS.filter(i => i.type === 'pattern').length },
    { value: 'gap', label: 'Gaps', count: MOCK_INSIGHTS.filter(i => i.type === 'gap').length },
    { value: 'strength', label: 'Strengths', count: MOCK_INSIGHTS.filter(i => i.type === 'strength').length },
    { value: 'opportunity', label: 'Opportunities', count: MOCK_INSIGHTS.filter(i => i.type === 'opportunity').length },
  ];

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="space-y-4">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold text-foreground">Portfolio Insights</h2>
          <p className="text-muted-foreground text-lg">
            Valuable patterns and opportunities discovered through AI analysis of your complete profile
          </p>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap items-center gap-3 pt-2">
          <span className="text-sm font-semibold text-muted-foreground">Filter:</span>
          {insightTypes.map((type) => (
            <Badge
              key={type.value}
              variant={selectedType === type.value ? 'default' : 'outline'}
              className="cursor-pointer hover:bg-primary/10 transition-colors"
              onClick={() => setSelectedType(type.value as any)}
            >
              {type.label} ({type.count})
            </Badge>
          ))}
          
          <div className="ml-auto flex items-center gap-2">
            <span className="text-sm font-semibold text-muted-foreground">Sort by:</span>
            <Badge
              variant={sortBy === 'priority' ? 'default' : 'outline'}
              className="cursor-pointer"
              onClick={() => setSortBy('priority')}
            >
              Priority
            </Badge>
            <Badge
              variant={sortBy === 'impact' ? 'default' : 'outline'}
              className="cursor-pointer"
              onClick={() => setSortBy('impact')}
            >
              Impact Score
            </Badge>
          </div>
        </div>
      </div>

      {/* Insights Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {sortedInsights.map((insight, index) => (
          <InsightCard key={index} {...insight} />
        ))}
      </div>

      {sortedInsights.length === 0 && (
        <div className="text-center py-12 text-muted-foreground">
          No insights found for the selected filter.
        </div>
      )}
    </div>
  );
};
