import React from 'react';
import { HoverCard, HoverCardTrigger, HoverCardContent } from '@/components/ui/hover-card';
import { LucideIcon, Rocket, Target, Heart, Sparkles, AlertTriangle } from 'lucide-react';

// Types
export interface KeyTakeaway {
  label: string;
  description: string;
  icon: LucideIcon;
  colorClass: string;
}

export type EvidenceProps = { text: string; details: string[] };
export type RichSegment = string | EvidenceProps;

export interface VerdictOption {
  id: string;
  text: RichSegment[];
  score: number;
  reasoning: string;
}

export interface StoryTellingOption {
  id: string;
  positioning: string;
  narrative: RichSegment[];
  score: number;
  reasoning: string;
}

export interface OverarchingInsight {
  verdictOptions: {
    spine: VerdictOption[];
    spike: VerdictOption[];
    lift: VerdictOption[];
  };
  storyTellingOptions: StoryTellingOption[];
  readinessInContext: RichSegment[];
  storyCoherencePercent: number;
  storyCoherenceLine: RichSegment[];
  impactFootprint: RichSegment[];
  recognitionMix: RichSegment[];
  trajectoryDurability: RichSegment[];
  contextContribution: RichSegment[];
  committeeSoundBite: RichSegment[];
}

export interface HolisticSummary {
  overallScore: number;
  tierName: string;
  tierPercentile: string;
  profileSummary: string;
  coreIdentity: KeyTakeaway;
  competitivePosition: KeyTakeaway;
  narrativeTheme: KeyTakeaway;
  biggestDifferentiator: KeyTakeaway;
  criticalGap: KeyTakeaway;
  overarchingInsight?: OverarchingInsight;
}

// Helper Components
const InlineEvidence: React.FC<EvidenceProps> = ({ text, details }) => (
  <HoverCard>
    <HoverCardTrigger asChild>
      <span className="underline decoration-dotted underline-offset-4 cursor-help text-sky-600 hover:text-sky-700">
        {text}
      </span>
    </HoverCardTrigger>
    <HoverCardContent align="start" className="w-80">
      <div className="text-sm font-semibold mb-1">Evidence</div>
      <ul className="list-disc pl-5 space-y-1 text-sm leading-6">
        {details.map((d, i) => (
          <li key={i} className="text-foreground/90">{d}</li>
        ))}
      </ul>
    </HoverCardContent>
  </HoverCard>
);

export const renderRich = (segments: RichSegment[]) =>
  segments.map((seg, i) =>
    typeof seg === 'string' ? <span key={i}>{seg}</span> : <InlineEvidence key={i} text={seg.text} details={seg.details} />
  );

// IMPORTANT: Hard-coded mock data representing a holistic portfolio analysis
// In production, this would be generated by AI analyzing the user's complete portfolio
// and synthesizing patterns across all dimensions, activities, and achievements
export const MOCK_HOLISTIC_SUMMARY: HolisticSummary = {
  overallScore: 8.2,
  tierName: 'Diamond Achiever',
  tierPercentile: 'Top 15%',
  profileSummary: 'You present as a community-focused STEM leader with demonstrated technical expertise, sustained volunteer commitment, and emerging research capabilities. Your portfolio shows cross-domain versatility, positioning you competitively for Top 20 schools with reach potential for Top 10.',
  coreIdentity: {
    label: 'STEM Leader & Community Catalyst',
    description: 'You consistently combine technical projects with community service, showing you can lead in both contexts.',
    icon: Rocket,
    colorClass: 'border-primary',
  },
  competitivePosition: {
    label: 'Strong T20, Reach for T10',
    description: 'Your profile aligns well with schools ranked 11-20. Stanford/MIT are reaches; schools like Duke/Northwestern are targets.',
    icon: Target,
    colorClass: 'border-purple-500',
  },
  narrativeTheme: {
    label: 'Using Technology to Democratize Access',
    description: 'Your story centers on leveraging technical skills to create opportunities for underserved communities.',
    icon: Heart,
    colorClass: 'border-green-500',
  },
  biggestDifferentiator: {
    label: 'Cross-Domain Leadership (Tech + Community)',
    description: 'Unlike most STEM students focused purely on research, you balance technical depth with genuine community impact.',
    icon: Sparkles,
    colorClass: 'border-orange-500',
  },
  criticalGap: {
    label: 'Need Quantifiable Impact Metrics',
    description: 'Your community activities lack specific numbers (people served, hours, outcomes), making impact hard to assess.',
    icon: AlertTriangle,
    colorClass: 'border-destructive',
  },
  overarchingInsight: {
    verdictOptions: {
      spine: [
        {
          id: 'civic-tech-democratizer',
          text: [
            'Your spine is clear: using technology to democratize access - from ',
            { text: 'Title I workshops', details: ['Free cycles for two Title I partners', 'Avg 24 students/session'] },
            ' to mentoring first-time coders via the ',
            { text: 'library program', details: ['Monthly beginner cohorts since Jan 2024', 'Consistent waitlist demand'] },
            '.'
          ],
          score: 9.2,
          reasoning: 'Strongest narrative thread - unifies technical skills, community impact, and leadership across all activities'
        },
        {
          id: 'education-equity-champion',
          text: [
            'You are an education equity champion who leverages ',
            { text: 'technical expertise', details: ['Full-stack platform, 118 weekly users', 'Adaptive controller kits for inclusion'] },
            ' to expand opportunity for underserved students, with a track record of ',
            { text: 'sustained mentorship', details: ['18 months tutoring program', '24 mentees across two cohorts'] },
            ' that demonstrates genuine investment beyond building.'
          ],
          score: 8.7,
          reasoning: 'Emphasizes social justice angle - highly valued but slightly narrower than democratization theme'
        },
        {
          id: 'systems-builder',
          text: [
            'You are a systems thinker who identifies inefficiencies and builds ',
            { text: 'scalable solutions', details: ['Platform architecture serves 2 schools', 'Open-source controller repo: 42 stars'] },
            ' that outlive your direct involvement, as evidenced by ',
            { text: 'handoff documentation', details: ['Onboarding checklist, weekly runbook', 'Successor training materials'] },
            ' ensuring continuity.'
          ],
          score: 8.3,
          reasoning: 'Highlights analytical and architectural abilities, but less emotionally resonant than access narrative'
        },
        {
          id: 'cross-disciplinary-connector',
          text: [
            'You bridge policy, data science, and community organizing - translating ',
            { text: 'budget PDFs into dashboards', details: ['Civic Tech Challenge finalist', 'Public changelog, partner quotes'] },
            ' while simultaneously running ',
            { text: 'hands-on programs', details: ['Weekly tutoring sessions', 'Monthly beginner workshops'] },
            ' that connect technical work to human outcomes.'
          ],
          score: 7.9,
          reasoning: 'Unique positioning but may seem unfocused without careful framing - requires precise essay execution'
        }
      ],
      spike: [
        {
          id: 'quantifiable-impact',
          text: [
            'Your ',
            { text: 'quantifiable community impact', details: ['118 students weekly through tutoring platform', 'MOUs with two partner schools', 'Tutor roster grew 6 to 19', 'Retention improving 12 pts'] },
            ' is exceptional - concrete adoption metrics and institutional partnerships that separate you from peers who claim "impact" without evidence.'
          ],
          score: 9.5,
          reasoning: 'Most distinctive spike - hard numbers validate claims and demonstrate scale rarely seen in high school portfolios'
        },
        {
          id: 'technical-leadership',
          text: [
            'A distinctive spike in engineering-for-access with real adoption - your ',
            { text: 'tutoring platform', details: ['118 weekly active students last month', 'MOUs with two partner schools', 'Tutor roster grew 6 to 19'] },
            ' consistently serves local schools, and the ',
            { text: 'adaptive controller kits', details: ['18 robotics members using kits', 'Open-source repo: 42 stars, 9 forks'] },
            ' lowered barriers for new participants.'
          ],
          score: 8.8,
          reasoning: 'Demonstrates technical maturity and sustained operation - shows you can shepherd projects from idea to adoption'
        },
        {
          id: 'external-validation',
          text: [
            'Your spike is in externally validated impact: ',
            { text: 'national finalist recognition', details: ['Civic Tech Challenge - finalist (top 10/1,200)'] },
            ' for civic technology combined with ',
            { text: 'state-level awards', details: ['State CS Olympiad - 2nd place', 'State Service Innovation Award - winner'] },
            ' that validate both technical craft and community contribution.'
          ],
          score: 8.4,
          reasoning: 'Third-party validation carries weight, but slightly weaker than direct adoption metrics'
        }
      ],
      lift: [
        {
          id: 'recognition-pursuit',
          text: [
            'Biggest lift: convert effort into public outcomes. Instead of logging hours, surface a compact metrics layer - a single ',
            { text: 'impact hub', details: ['One page consolidating beneficiaries, before/after, artifacts, testimonials'] },
            ' that quantifies who benefited and how across programs.'
          ],
          score: 9.0,
          reasoning: 'Most critical gap - you have strong work that lacks third-party validation. National competitions would dramatically strengthen credibility'
        },
        {
          id: 'leadership-breadth',
          text: [
            'You should ',
            { text: 'expand leadership beyond tech', details: ['Consider student government role', 'Arts/culture leadership opportunity', 'Cross-domain club presidency'] },
            ' to demonstrate versatility. Your technical leadership is clear, but schools want to see you can lead in contexts where you\'re not the expert.'
          ],
          score: 7.5,
          reasoning: 'Would strengthen well-roundedness, but lower priority than recognition - your tech leadership is already strong'
        }
      ]
    },
    storyTellingOptions: [
      {
        id: 'civic-tech-narrative',
        positioning: 'Civic-Tech Builder',
        narrative: [
          'Frame your application around: building technology for civic good. Lead with the ',
          { text: 'tutoring platform', details: ['118 weekly active students', 'Two schools', 'Retention improving'] },
          ' as living proof of impact at scale. In your personal statement, focus on the moment you realized code could ',
          { text: 'democratize access', details: ['Title I workshops expanding reach', 'Library program removing barriers'] },
          ' to education. Position supplements around how each project serves underserved communities. This narrative aligns perfectly with top-tier college values (innovation + equity).'
        ],
        score: 9.1,
        reasoning: 'Best aligns with top-tier college values - innovation paired with social impact. Most compelling for T10 schools'
      },
      {
        id: 'equity-advocate-narrative',
        positioning: 'Education Equity Advocate',
        narrative: [
          'Position yourself as someone who uses tech to expand opportunity. Center your ',
          { text: 'sustained mentorship', details: ['18 months tutoring program', '24 mentees across cohorts', 'Documented skill progression'] },
          ' and frame the platform as a tool that emerged from seeing tutors struggle with coordination. Personal statement should explore your ',
          { text: 'identity connection', details: ['First-gen college aspirant', 'Resource constraints shaped perspective'] },
          ' to access issues. This narrative is powerful but requires authentic personal connection to avoid seeming performative.'
        ],
        score: 8.6,
        reasoning: 'Strong social justice angle - highly valued but competitive. Requires authentic personal connection to resonate'
      },
      {
        id: 'systems-thinker-narrative',
        positioning: 'Technical Systems Architect',
        narrative: [
          'Tell the story of someone who sees inefficient systems and builds ',
          { text: 'scalable solutions', details: ['Platform architecture', 'Open-source contributions', 'Handoff documentation'] },
          '. Your narrative centers on sustainability - projects that ',
          { text: 'outlive your involvement', details: ['Documented handoffs', 'Successor training', 'Maintained operations'] },
          '. This positions you as mature and systems-oriented, ideal for engineering programs that value architectural thinking.'
        ],
        score: 8.2,
        reasoning: 'Appeals to technical programs but less emotionally compelling - best for pure CS/engineering applications'
      },
      {
        id: 'policy-to-action-narrative',
        positioning: 'Policy-to-Action Translator',
        narrative: [
          'Frame yourself as bridging the gap between policy and implementation. Start with ',
          { text: 'civic tech work', details: ['Budget visualization dashboard', 'Policy data made accessible'] },
          ' and show how this connects to hands-on programs. Position your technical skills as a means to ',
          { text: 'translate complex systems', details: ['Data visualization for accessibility', 'Platform reducing coordination friction'] },
          ' into actionable tools. This narrative works well for schools with strong public policy + CS intersections (Stanford, Harvard, Princeton).'
        ],
        score: 7.8,
        reasoning: 'Unique angle but requires careful execution - risk of seeming scattered across too many domains'
      }
    ],
    readinessInContext: [
      'Readiness is strong relative to availability: you maximized rigor and show an upward trend. With ',
      { text: 'limited AP availability', details: ['School profile lists 6 AP vs district 12'] },
      ' you still hit the ceiling; the transcript climbs from 10th grade, and dual-enrolling in ',
      { text: 'Multivariable', details: ['College Multivariable completed with A-', 'Linear Algebra in progress'] },
      ' validates preparation for upper-division work.'
    ],
    storyCoherencePercent: 78,
    storyCoherenceLine: [
      'Coherence sits at 78%: 7 of 9 activities and your main essays reinforce the access theme. The personal statement focuses on ',
      { text: 'assistive tech for access', details: ['Draft PS references accessibility outcomes and user testing notes'] },
      ', which is echoed by recommenders who highlight your teaching-and-buildership pattern.'
    ],
    impactFootprint: [
      'Impact concentrates in education access. The ',
      { text: 'tutoring platform', details: ['118 weekly active students; two partner schools; retention improving 12 pts'] },
      ' reduces friction for students and coordinators, while ',
      { text: 'workshop series', details: ['Three cycles delivered; avg 24 students/session; pre/post quiz gains 18%'] },
      ' expands reach beyond your school.'
    ],
    recognitionMix: [
      'Credibility is supported by external reads: ',
      { text: 'national finalist', details: ['Civic Tech Challenge - finalist (top 10/1,200)'] },
      ', ',
      { text: 'two state-level awards', details: ['State CS Olympiad - 2nd place', 'State Service Innovation Award - winner'] },
      ', and multiple school honors. This ladder validates both craft and contribution.'
    ],
    trajectoryDurability: [
      'Trajectory points up and the work outlives you. You progressed from tutor to program ',
      { text: 'director', details: ['Tutor to coordinator to director; scope expanded to two schools'] },
      ', built written playbooks, and trained successors for two orgs. Durability is visible in maintained schedules and ',
      { text: 'handoff docs', details: ['Shared drive: onboarding checklist, weekly runbook, escalation contacts'] },
      ' that keep services running.'
    ],
    contextContribution: [
      'Context reframes choices: despite ',
      { text: 'limited AP availability', details: ['School offers 6 AP vs district 12'] },
      ', you expanded rigor via college math and contributed to an ',
      { text: 'open-source repo', details: ['Regular issues/PRs across 6 months; 42 stars; 9 forks'] },
      ', signaling initiative and community orientation.'
    ],
    committeeSoundBite: [
      '"Admit as the ',
      { text: 'civic-tech builder', details: ['Budget PDF to dashboard prototype; partner quotes; public changelog'] },
      ' who turns messy policy data into tools people actually use."'
    ]
  }
};
